### ISSUE TITLE
Unknown option -e

### ISSUE THREAD

**Issue by TangMonk** [qhwa/aliyun-oss-sync#4]
```
/usr/local/rvm/gems/ruby-2.1.5/gems/gli-2.9.0/lib/gli/gli_option_block_parser.rb:19:in `block in initialize'
/usr/local/rvm/gems/ruby-2.1.5/gems/gli-2.9.0/lib/gli/gli_option_block_parser.rb:35:in `call'
/usr/local/rvm/gems/ruby-2.1.5/gems/gli-2.9.0/lib/gli/gli_option_block_parser.rb:35:in `rescue in parse!'
/usr/local/rvm/gems/ruby-2.1.5/gems/gli-2.9.0/lib/gli/gli_option_block_parser.rb:33:in `parse!'
/usr/local/rvm/gems/ruby-2.1.5/gems/gli-2.9.0/lib/gli/gli_option_parser.rb:31:in `parse!'
/usr/local/rvm/gems/ruby-2.1.5/gems/gli-2.9.0/lib/gli/gli_option_parser.rb:16:in `block in parse_options'
/usr/local/rvm/gems/ruby-2.1.5/gems/gli-2.9.0/lib/gli/gli_option_parser.rb:14:in `tap'
/usr/local/rvm/gems/ruby-2.1.5/gems/gli-2.9.0/lib/gli/gli_option_parser.rb:14:in `parse_options'
/usr/local/rvm/gems/ruby-2.1.5/gems/gli-2.9.0/lib/gli/app_support.rb:73:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/aliyun-oss-sync-0.0.1/bin/aliyun-oss-sync:82:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/aliyun-oss-sync:23:in `load'
/usr/local/rvm/gems/ruby-2.1.5/bin/aliyun-oss-sync:23:in `<main>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
error: Unknown option -e

NAME
    aliyun-oss-sync - aliyun oss sync

SYNOPSIS
    aliyun-oss-sync [global options] command [command options] [arguments...]

VERSION
    0.0.1

GLOBAL OPTIONS
    --help           - Show this message
    -k, --key=arg    - aliyun access key id (default: none)
    -s, --secret=arg - aliyun access key secret (default: none)
    --version        - Display the program version

COMMANDS
    help - Shows a list of commands or help for one command
    pull - pull files from Aliyun OSS to local directory
    push - push files from local directory to Aliyun OSS
    sync - sync files between local directory and Aliyun OSS
```

这个，怎么和文档上写的不一样啊。。没有-e的选项

**Comment by lazywhite** [comment]
same error too
